// src/lib/mock-data.ts
// Central demo data — all types defined inline to avoid circular imports

export const DEMO_USER_ID = 'usr-demo-1';
export const DEMO_PIPELINE_ID = 'pip-main-1';

export const DEMO_USER = {
  id: DEMO_USER_ID,
  email: 'demo@alozix.com',
  firstName: 'Demo',
  lastName: 'User',
  phone: null as string | null,
  avatarUrl: null as string | null,
  createdAt: '2024-01-01T00:00:00.000Z',
  updatedAt: '2024-01-01T00:00:00.000Z',
  role: 'OWNER' as const,
};

export const DEMO_PIPELINE = {
  id: DEMO_PIPELINE_ID,
  name: 'Main Pipeline',
  isDefault: true,
  archivedAt: null as string | null,
};

export const DEMO_STAGES = [
  { id: 'stg-prospect', pipelineId: DEMO_PIPELINE_ID, name: 'Prospect', position: 0, isClosedWon: false, isClosedLost: false, archivedAt: null as string | null },
  { id: 'stg-proposal', pipelineId: DEMO_PIPELINE_ID, name: 'Proposal', position: 1, isClosedWon: false, isClosedLost: false, archivedAt: null as string | null },
  { id: 'stg-negotiation', pipelineId: DEMO_PIPELINE_ID, name: 'Negotiation', position: 2, isClosedWon: false, isClosedLost: false, archivedAt: null as string | null },
  { id: 'stg-won', pipelineId: DEMO_PIPELINE_ID, name: 'Won', position: 3, isClosedWon: true, isClosedLost: false, archivedAt: null as string | null },
  { id: 'stg-lost', pipelineId: DEMO_PIPELINE_ID, name: 'Lost', position: 4, isClosedWon: false, isClosedLost: true, archivedAt: null as string | null },
];

export const DEMO_LEAD_SOURCE = { id: 'ls-001', name: 'Website' };

export const DEMO_CONTACTS = [
  {
    id: 'cnt-001',
    firstName: 'Alice',
    lastName: 'Example',
    email: 'alice@example.com',
    phone: '+1-555-0101',
    status: 'CUSTOMER' as const,
    tags: [{ id: 'ct-001', tagId: 'tag-001', tag: { id: 'tag-001', name: 'VIP', color: null } }],
    companyId: 'cmp-demo',
    ownerId: DEMO_USER_ID,
    leadSourceId: 'ls-001',
    archivedAt: null as string | null,
    createdAt: '2024-02-01T10:00:00.000Z',
    updatedAt: '2024-02-01T10:00:00.000Z',
    owner: { id: DEMO_USER_ID, firstName: 'Demo', lastName: 'User', email: 'demo@alozix.com' },
    leadSource: DEMO_LEAD_SOURCE,
  },
  {
    id: 'cnt-002',
    firstName: 'Bob',
    lastName: 'Sample',
    email: 'bob@sample.org',
    phone: '+1-555-0102',
    status: 'PROSPECT' as const,
    tags: [] as Array<{ id: string; tagId: string; tag: { id: string; name: string; color: string | null } }>,
    companyId: 'cmp-demo',
    ownerId: DEMO_USER_ID,
    leadSourceId: 'ls-001',
    archivedAt: null as string | null,
    createdAt: '2024-03-01T10:00:00.000Z',
    updatedAt: '2024-03-01T10:00:00.000Z',
    owner: { id: DEMO_USER_ID, firstName: 'Demo', lastName: 'User', email: 'demo@alozix.com' },
    leadSource: DEMO_LEAD_SOURCE,
  },
  {
    id: 'cnt-003',
    firstName: 'Carol',
    lastName: 'Demo',
    email: 'carol@demo.io',
    phone: '+1-555-0103',
    status: 'CUSTOMER' as const,
    tags: [{ id: 'ct-002', tagId: 'tag-002', tag: { id: 'tag-002', name: 'Partner', color: null } }],
    companyId: 'cmp-demo',
    ownerId: DEMO_USER_ID,
    leadSourceId: null as string | null,
    archivedAt: null as string | null,
    createdAt: '2024-04-01T10:00:00.000Z',
    updatedAt: '2024-04-01T10:00:00.000Z',
    owner: { id: DEMO_USER_ID, firstName: 'Demo', lastName: 'User', email: 'demo@alozix.com' },
    leadSource: null,
  },
  {
    id: 'cnt-004',
    firstName: 'David',
    lastName: 'Testuser',
    email: 'david@testuser.net',
    phone: '+1-555-0104',
    status: 'PROSPECT' as const,
    tags: [] as Array<{ id: string; tagId: string; tag: { id: string; name: string; color: string | null } }>,
    companyId: 'cmp-demo',
    ownerId: DEMO_USER_ID,
    leadSourceId: null as string | null,
    archivedAt: null as string | null,
    createdAt: '2024-05-01T10:00:00.000Z',
    updatedAt: '2024-05-01T10:00:00.000Z',
    owner: { id: DEMO_USER_ID, firstName: 'Demo', lastName: 'User', email: 'demo@alozix.com' },
    leadSource: null,
  },
  {
    id: 'cnt-005',
    firstName: 'Eve',
    lastName: 'Placeholder',
    email: 'eve@placeholder.dev',
    phone: null as string | null,
    status: 'ARCHIVED' as const,
    tags: [] as Array<{ id: string; tagId: string; tag: { id: string; name: string; color: string | null } }>,
    companyId: 'cmp-demo',
    ownerId: null as string | null,
    leadSourceId: null as string | null,
    archivedAt: '2024-06-01T10:00:00.000Z',
    createdAt: '2024-06-01T10:00:00.000Z',
    updatedAt: '2024-06-01T10:00:00.000Z',
    owner: null,
    leadSource: null,
  },
];

export const DEMO_LEADS = [
  {
    id: 'led-001',
    companyId: 'cmp-demo',
    firstName: 'Frank',
    lastName: 'DemoLead',
    email: 'frank@demolead.com',
    phone: '+1-555-0201',
    status: 'NEW' as const,
    stage: 'NEW' as const,
    temperature: 'HOT' as const,
    ownerId: DEMO_USER_ID,
    nextFollowUpAt: null as string | null,
    source: 'WEBSITE' as const,
    sourceDetail: null as string | null,
    leadSourceId: 'ls-001',
    originalMessage: null as string | null,
    linkedConversationId: null as string | null,
    linkedConversationProvider: null as string | null,
    externalSourceId: null as string | null,
    convertedContactId: null as string | null,
    convertedAt: null as string | null,
    createdAt: '2024-06-15T10:00:00.000Z',
    updatedAt: '2024-06-15T10:00:00.000Z',
    owner: { id: DEMO_USER_ID, firstName: 'Demo', lastName: 'User', email: 'demo@alozix.com' },
    leadSource: DEMO_LEAD_SOURCE,
    convertedContact: null,
  },
  {
    id: 'led-002',
    companyId: 'cmp-demo',
    firstName: 'Grace',
    lastName: 'SampleLead',
    email: 'grace@samplelead.io',
    phone: '+1-555-0202',
    status: 'CONTACTED' as const,
    stage: 'CONTACTED' as const,
    temperature: 'WARM' as const,
    ownerId: DEMO_USER_ID,
    nextFollowUpAt: null as string | null,
    source: 'INSTAGRAM' as const,
    sourceDetail: null as string | null,
    leadSourceId: null as string | null,
    originalMessage: 'Interested in your services',
    linkedConversationId: null as string | null,
    linkedConversationProvider: null as string | null,
    externalSourceId: null as string | null,
    convertedContactId: null as string | null,
    convertedAt: null as string | null,
    createdAt: '2024-07-01T10:00:00.000Z',
    updatedAt: '2024-07-01T10:00:00.000Z',
    owner: { id: DEMO_USER_ID, firstName: 'Demo', lastName: 'User', email: 'demo@alozix.com' },
    leadSource: null,
    convertedContact: null,
  },
  {
    id: 'led-003',
    companyId: 'cmp-demo',
    firstName: 'Henry',
    lastName: 'FakeLead',
    email: null as string | null,
    phone: '+1-555-0203',
    status: 'FOLLOW_UP_NEEDED' as const,
    stage: 'CONTACTED' as const,
    temperature: 'COLD' as const,
    ownerId: null as string | null,
    nextFollowUpAt: null as string | null,
    source: 'REFERRAL' as const,
    sourceDetail: null as string | null,
    leadSourceId: null as string | null,
    originalMessage: null as string | null,
    linkedConversationId: null as string | null,
    linkedConversationProvider: null as string | null,
    externalSourceId: null as string | null,
    convertedContactId: null as string | null,
    convertedAt: null as string | null,
    createdAt: '2024-07-10T10:00:00.000Z',
    updatedAt: '2024-07-10T10:00:00.000Z',
    owner: null,
    leadSource: null,
    convertedContact: null,
  },
  {
    id: 'led-004',
    companyId: 'cmp-demo',
    firstName: 'Iris',
    lastName: 'TestLead',
    email: 'iris@testlead.org',
    phone: null as string | null,
    status: 'WON' as const,
    stage: 'WON' as const,
    temperature: null as string | null,
    ownerId: DEMO_USER_ID,
    nextFollowUpAt: null as string | null,
    source: 'PHONE' as const,
    sourceDetail: null as string | null,
    leadSourceId: null as string | null,
    originalMessage: null as string | null,
    linkedConversationId: null as string | null,
    linkedConversationProvider: null as string | null,
    externalSourceId: null as string | null,
    convertedContactId: null as string | null,
    convertedAt: null as string | null,
    createdAt: '2024-07-15T10:00:00.000Z',
    updatedAt: '2024-08-01T10:00:00.000Z',
    owner: { id: DEMO_USER_ID, firstName: 'Demo', lastName: 'User', email: 'demo@alozix.com' },
    leadSource: null,
    convertedContact: null,
  },
  {
    id: 'led-005',
    companyId: 'cmp-demo',
    firstName: 'Jack',
    lastName: 'ExampleLead',
    email: 'jack@examplelead.com',
    phone: '+1-555-0205',
    status: 'LOST' as const,
    stage: 'LOST' as const,
    temperature: 'COLD' as const,
    ownerId: null as string | null,
    nextFollowUpAt: null as string | null,
    source: 'FACEBOOK' as const,
    sourceDetail: null as string | null,
    leadSourceId: null as string | null,
    originalMessage: null as string | null,
    linkedConversationId: null as string | null,
    linkedConversationProvider: null as string | null,
    externalSourceId: null as string | null,
    convertedContactId: null as string | null,
    convertedAt: null as string | null,
    createdAt: '2024-08-05T10:00:00.000Z',
    updatedAt: '2024-08-05T10:00:00.000Z',
    owner: null,
    leadSource: null,
    convertedContact: null,
  },
];

const DEMO_ASSIGNEE_SUMMARY = {
  id: DEMO_USER_ID,
  displayName: 'Demo User',
  email: 'demo@alozix.com',
};

export const DEMO_TASKS = [
  {
    id: 'tsk-001',
    taskType: 'GENERAL' as const,
    entityType: 'CONTACT' as const,
    entityId: 'cnt-001',
    title: 'Follow up with Alice',
    description: 'Send the proposal document',
    dueAt: '2026-07-15T09:00:00.000Z',
    status: 'TODO' as const,
    completedAt: null as string | null,
    assigneeId: DEMO_USER_ID,
    createdAt: '2024-09-01T10:00:00.000Z',
    updatedAt: '2024-09-01T10:00:00.000Z',
    entitySummary: { id: 'cnt-001', type: 'CONTACT' as const, displayName: 'Alice Example', status: 'CUSTOMER', temperature: null },
    assigneeSummary: DEMO_ASSIGNEE_SUMMARY,
  },
  {
    id: 'tsk-002',
    taskType: 'GENERAL' as const,
    entityType: 'DEAL' as const,
    entityId: 'dea-001',
    title: 'Prepare sample deal contract',
    description: null as string | null,
    dueAt: '2026-07-18T09:00:00.000Z',
    status: 'IN_PROGRESS' as const,
    completedAt: null as string | null,
    assigneeId: DEMO_USER_ID,
    createdAt: '2024-09-05T10:00:00.000Z',
    updatedAt: '2024-09-05T10:00:00.000Z',
    entitySummary: { id: 'dea-001', type: 'DEAL' as const, displayName: 'Demo Website Project', status: 'OPEN', temperature: null },
    assigneeSummary: DEMO_ASSIGNEE_SUMMARY,
  },
  {
    id: 'tsk-003',
    taskType: 'FOLLOW_UP' as const,
    entityType: 'LEAD' as const,
    entityId: 'led-001',
    title: 'Schedule intro call with Frank',
    description: 'Hot lead — prioritize',
    dueAt: '2026-07-10T09:00:00.000Z',
    status: 'WAITING' as const,
    completedAt: null as string | null,
    assigneeId: DEMO_USER_ID,
    createdAt: '2024-09-10T10:00:00.000Z',
    updatedAt: '2024-09-10T10:00:00.000Z',
    entitySummary: { id: 'led-001', type: 'LEAD' as const, displayName: 'Frank DemoLead', status: 'NEW', temperature: 'HOT' },
    assigneeSummary: DEMO_ASSIGNEE_SUMMARY,
  },
  {
    id: 'tsk-006',
    taskType: 'FOLLOW_UP' as const,
    entityType: 'LEAD' as const,
    entityId: 'led-001',
    title: 'Call the lead about the proposal',
    description: 'Discussed needs',
    dueAt: '2024-06-17T09:00:00.000Z',
    status: 'DONE' as const,
    completedAt: '2026-07-21T11:40:00.000Z',
    assigneeId: DEMO_USER_ID,
    createdAt: '2024-06-16T15:20:00.000Z',
    updatedAt: '2026-07-21T11:40:00.000Z',
    entitySummary: { id: 'led-001', type: 'LEAD' as const, displayName: 'Frank DemoLead', status: 'NEW', temperature: 'HOT' },
    assigneeSummary: DEMO_ASSIGNEE_SUMMARY,
  },
  {
    id: 'tsk-007',
    taskType: 'FOLLOW_UP' as const,
    entityType: 'LEAD' as const,
    entityId: 'led-002',
    title: 'Follow up with Grace SampleLead',
    description: 'Confirm project scope and next steps',
    dueAt: '2026-07-21T09:00:00.000Z',
    status: 'TODO' as const,
    completedAt: null as string | null,
    assigneeId: DEMO_USER_ID,
    createdAt: '2026-07-20T10:00:00.000Z',
    updatedAt: '2026-07-20T10:00:00.000Z',
    entitySummary: { id: 'led-002', type: 'LEAD' as const, displayName: 'Grace SampleLead', status: 'CONTACTED', temperature: 'WARM' },
    assigneeSummary: DEMO_ASSIGNEE_SUMMARY,
  },
  {
    id: 'tsk-008',
    taskType: 'FOLLOW_UP' as const,
    entityType: 'LEAD' as const,
    entityId: 'led-003',
    title: 'Prepare proposal for Henry FakeLead',
    description: null as string | null,
    dueAt: '2026-07-21T14:00:00.000Z',
    status: 'TODO' as const,
    completedAt: null as string | null,
    assigneeId: DEMO_USER_ID,
    createdAt: '2026-07-20T11:00:00.000Z',
    updatedAt: '2026-07-20T11:00:00.000Z',
    entitySummary: { id: 'led-003', type: 'LEAD' as const, displayName: 'Henry FakeLead', status: 'FOLLOW_UP_NEEDED', temperature: 'COLD' },
    assigneeSummary: DEMO_ASSIGNEE_SUMMARY,
  },
  {
    id: 'tsk-009',
    taskType: 'FOLLOW_UP' as const,
    entityType: 'LEAD' as const,
    entityId: 'led-004',
    title: 'Call Iris TestLead',
    description: null as string | null,
    dueAt: '2026-07-22T10:00:00.000Z',
    status: 'TODO' as const,
    completedAt: null as string | null,
    assigneeId: DEMO_USER_ID,
    createdAt: '2026-07-20T12:00:00.000Z',
    updatedAt: '2026-07-20T12:00:00.000Z',
    entitySummary: { id: 'led-004', type: 'LEAD' as const, displayName: 'Iris TestLead', status: 'WON', temperature: null },
    assigneeSummary: DEMO_ASSIGNEE_SUMMARY,
  },
  {
    id: 'tsk-010',
    taskType: 'FOLLOW_UP' as const,
    entityType: 'LEAD' as const,
    entityId: 'led-005',
    title: 'Send quote to Jack ExampleLead',
    description: null as string | null,
    dueAt: '2026-07-23T11:30:00.000Z',
    status: 'TODO' as const,
    completedAt: null as string | null,
    assigneeId: null as string | null,
    createdAt: '2026-07-20T13:00:00.000Z',
    updatedAt: '2026-07-20T13:00:00.000Z',
    entitySummary: { id: 'led-005', type: 'LEAD' as const, displayName: 'Jack ExampleLead', status: 'LOST', temperature: 'COLD' },
    assigneeSummary: null,
  },
  {
    id: 'tsk-004',
    taskType: 'GENERAL' as const,
    entityType: 'CONTACT' as const,
    entityId: 'cnt-002',
    title: 'Send sample brochure to Bob',
    description: null as string | null,
    dueAt: null as string | null,
    status: 'DONE' as const,
    completedAt: '2024-09-12T10:00:00.000Z',
    assigneeId: DEMO_USER_ID,
    createdAt: '2024-09-11T10:00:00.000Z',
    updatedAt: '2024-09-12T10:00:00.000Z',
    entitySummary: { id: 'cnt-002', type: 'CONTACT' as const, displayName: 'Bob Sample', status: 'PROSPECT', temperature: null },
    assigneeSummary: DEMO_ASSIGNEE_SUMMARY,
  },
  {
    id: 'tsk-005',
    taskType: 'GENERAL' as const,
    entityType: 'DEAL' as const,
    entityId: 'dea-002',
    title: 'Review placeholder deal terms',
    description: 'Check pricing',
    dueAt: '2026-07-22T09:00:00.000Z',
    status: 'TODO' as const,
    completedAt: null as string | null,
    assigneeId: null as string | null,
    createdAt: '2024-09-15T10:00:00.000Z',
    updatedAt: '2024-09-15T10:00:00.000Z',
    entitySummary: { id: 'dea-002', type: 'DEAL' as const, displayName: 'Example Service Retainer', status: 'OPEN', temperature: null },
    assigneeSummary: null,
  },
];

export const DEMO_DEALS = [
  {
    id: 'dea-001',
    pipelineId: DEMO_PIPELINE_ID,
    stageId: 'stg-proposal',
    contactId: 'cnt-001',
    ownerId: DEMO_USER_ID,
    leadSourceId: null as string | null,
    title: 'Demo Website Project',
    value: 5000,
    currency: 'USD',
    status: 'OPEN' as const,
    closedAt: null as string | null,
    expectedCloseAt: '2026-08-01T00:00:00.000Z',
    createdAt: '2024-10-01T10:00:00.000Z',
    updatedAt: '2024-10-01T10:00:00.000Z',
    contact: { id: 'cnt-001', firstName: 'Alice', lastName: 'Example', email: 'alice@example.com', phone: '+1-555-0101', status: 'CUSTOMER' },
    stage: { id: 'stg-proposal', name: 'Proposal', position: 1, pipelineId: DEMO_PIPELINE_ID, isClosedWon: false, isClosedLost: false, archivedAt: null },
    pipeline: { id: DEMO_PIPELINE_ID, name: 'Main Pipeline', isDefault: true, archivedAt: null },
    owner: { id: DEMO_USER_ID, firstName: 'Demo', lastName: 'User', email: 'demo@alozix.com' },
    leadSource: null,
  },
  {
    id: 'dea-002',
    pipelineId: DEMO_PIPELINE_ID,
    stageId: 'stg-prospect',
    contactId: 'cnt-002',
    ownerId: DEMO_USER_ID,
    leadSourceId: null as string | null,
    title: 'Example Service Retainer',
    value: 2500,
    currency: 'USD',
    status: 'OPEN' as const,
    closedAt: null as string | null,
    expectedCloseAt: null as string | null,
    createdAt: '2024-10-10T10:00:00.000Z',
    updatedAt: '2024-10-10T10:00:00.000Z',
    contact: { id: 'cnt-002', firstName: 'Bob', lastName: 'Sample', email: 'bob@sample.org', phone: '+1-555-0102', status: 'PROSPECT' },
    stage: { id: 'stg-prospect', name: 'Prospect', position: 0, pipelineId: DEMO_PIPELINE_ID, isClosedWon: false, isClosedLost: false, archivedAt: null },
    pipeline: { id: DEMO_PIPELINE_ID, name: 'Main Pipeline', isDefault: true, archivedAt: null },
    owner: { id: DEMO_USER_ID, firstName: 'Demo', lastName: 'User', email: 'demo@alozix.com' },
    leadSource: null,
  },
  {
    id: 'dea-003',
    pipelineId: DEMO_PIPELINE_ID,
    stageId: 'stg-won',
    contactId: 'cnt-003',
    ownerId: DEMO_USER_ID,
    leadSourceId: null as string | null,
    title: 'Sample Consulting Package',
    value: 10000,
    currency: 'USD',
    status: 'WON' as const,
    closedAt: '2024-11-01T10:00:00.000Z',
    expectedCloseAt: '2024-11-01T00:00:00.000Z',
    createdAt: '2024-09-01T10:00:00.000Z',
    updatedAt: '2024-11-01T10:00:00.000Z',
    contact: { id: 'cnt-003', firstName: 'Carol', lastName: 'Demo', email: 'carol@demo.io', phone: '+1-555-0103', status: 'CUSTOMER' },
    stage: { id: 'stg-won', name: 'Won', position: 3, pipelineId: DEMO_PIPELINE_ID, isClosedWon: true, isClosedLost: false, archivedAt: null },
    pipeline: { id: DEMO_PIPELINE_ID, name: 'Main Pipeline', isDefault: true, archivedAt: null },
    owner: { id: DEMO_USER_ID, firstName: 'Demo', lastName: 'User', email: 'demo@alozix.com' },
    leadSource: null,
  },
  {
    id: 'dea-004',
    pipelineId: DEMO_PIPELINE_ID,
    stageId: 'stg-lost',
    contactId: 'cnt-004',
    ownerId: null as string | null,
    leadSourceId: null as string | null,
    title: 'Placeholder Enterprise Deal',
    value: 0,
    currency: 'USD',
    status: 'LOST' as const,
    closedAt: '2024-10-20T10:00:00.000Z',
    expectedCloseAt: null as string | null,
    createdAt: '2024-09-15T10:00:00.000Z',
    updatedAt: '2024-10-20T10:00:00.000Z',
    contact: { id: 'cnt-004', firstName: 'David', lastName: 'Testuser', email: 'david@testuser.net', phone: '+1-555-0104', status: 'PROSPECT' },
    stage: { id: 'stg-lost', name: 'Lost', position: 4, pipelineId: DEMO_PIPELINE_ID, isClosedWon: false, isClosedLost: true, archivedAt: null },
    pipeline: { id: DEMO_PIPELINE_ID, name: 'Main Pipeline', isDefault: true, archivedAt: null },
    owner: null,
    leadSource: null,
  },
];

export const DEMO_ORDERS = [
  {
    id: 'ord-001',
    companyId: 'cmp-demo',
    contactId: 'cnt-001',
    conversationId: null as string | null,
    assigneeId: DEMO_USER_ID,
    title: 'Demo Order #1',
    description: 'Sample product delivery',
    status: 'IN_PROGRESS' as const,
    paymentStatus: 'PAID' as const,
    totalAmount: 500,
    currency: 'USD',
    expectedAt: '2026-08-01T00:00:00.000Z',
    createdAt: '2024-11-01T10:00:00.000Z',
    updatedAt: '2024-11-01T10:00:00.000Z',
    contact: { id: 'cnt-001', firstName: 'Alice', lastName: 'Example', email: 'alice@example.com', phone: '+1-555-0101', status: 'CUSTOMER' as const, archivedAt: null as string | null },
    conversation: null,
    assignee: { id: DEMO_USER_ID, firstName: 'Demo', lastName: 'User', email: 'demo@alozix.com' },
  },
  {
    id: 'ord-002',
    companyId: 'cmp-demo',
    contactId: 'cnt-002',
    conversationId: null as string | null,
    assigneeId: null as string | null,
    title: 'Example Order #2',
    description: null as string | null,
    status: 'NEW' as const,
    paymentStatus: 'UNPAID' as const,
    totalAmount: 250,
    currency: 'USD',
    expectedAt: null as string | null,
    createdAt: '2024-11-10T10:00:00.000Z',
    updatedAt: '2024-11-10T10:00:00.000Z',
    contact: { id: 'cnt-002', firstName: 'Bob', lastName: 'Sample', email: 'bob@sample.org', phone: '+1-555-0102', status: 'PROSPECT' as const, archivedAt: null as string | null },
    conversation: null,
    assignee: null,
  },
  {
    id: 'ord-003',
    companyId: 'cmp-demo',
    contactId: 'cnt-003',
    conversationId: null as string | null,
    assigneeId: DEMO_USER_ID,
    title: 'Sample Order #3',
    description: 'Placeholder consulting hours',
    status: 'FULFILLED' as const,
    paymentStatus: 'PAID' as const,
    totalAmount: 1000,
    currency: 'USD',
    expectedAt: '2024-12-01T00:00:00.000Z',
    createdAt: '2024-11-15T10:00:00.000Z',
    updatedAt: '2024-12-01T10:00:00.000Z',
    contact: { id: 'cnt-003', firstName: 'Carol', lastName: 'Demo', email: 'carol@demo.io', phone: '+1-555-0103', status: 'CUSTOMER' as const, archivedAt: null as string | null },
    conversation: null,
    assignee: { id: DEMO_USER_ID, firstName: 'Demo', lastName: 'User', email: 'demo@alozix.com' },
  },
];

export const DEMO_NOTES = [
  {
    id: 'note-001',
    entityType: 'CONTACT' as const,
    entityId: 'cnt-001',
    body: 'Called Alice — she is interested in the proposal.',
    authorId: DEMO_USER_ID,
    createdAt: '2024-09-02T10:00:00.000Z',
    updatedAt: '2024-09-02T10:00:00.000Z',
  },
  {
    id: 'note-002',
    entityType: 'DEAL' as const,
    entityId: 'dea-001',
    body: 'Sent draft contract for review.',
    authorId: DEMO_USER_ID,
    createdAt: '2024-10-05T10:00:00.000Z',
    updatedAt: '2024-10-05T10:00:00.000Z',
  },
];

export const DEMO_ACTIVITIES = [
  {
    id: 'act-001',
    entityType: 'CONTACT' as const,
    entityId: 'cnt-001',
    actorId: DEMO_USER_ID,
    actorType: 'USER' as const,
    actorDisplayName: 'Demo User',
    kind: 'CHANGE' as const,
    action: 'NOTE_ADDED',
    payload: {},
    changes: null,
    comment: null,
    reason: null,
    parentActivityId: null,
    relatedTaskId: null,
    companyId: 'cmp-demo',
    createdAt: '2024-09-02T10:00:00.000Z',
    editedAt: null as string | null,
  },
  {
    id: 'act-002',
    entityType: 'DEAL' as const,
    entityId: 'dea-001',
    actorId: DEMO_USER_ID,
    actorType: 'USER' as const,
    actorDisplayName: 'Demo User',
    kind: 'CHANGE' as const,
    action: 'STAGE_CHANGED',
    payload: {},
    changes: null,
    comment: null,
    reason: null,
    parentActivityId: null,
    relatedTaskId: null,
    companyId: 'cmp-demo',
    createdAt: '2024-10-02T10:00:00.000Z',
    editedAt: null as string | null,
  },
  {
    id: 'act-003',
    entityType: 'LEAD' as const,
    entityId: 'led-001',
    actorId: DEMO_USER_ID,
    actorType: 'USER' as const,
    actorDisplayName: 'Demo User',
    kind: 'CHANGE' as const,
    action: 'lead.updated',
    payload: {
      changes: [
        { field: 'temperature', label: 'Temperature', from: 'WARM', to: 'HOT' },
      ],
    },
    changes: [
      { field: 'temperature', label: 'Temperature', from: 'WARM', to: 'HOT' },
    ],
    comment: null,
    reason: null,
    parentActivityId: null,
    relatedTaskId: null,
    companyId: 'cmp-demo',
    createdAt: '2024-06-16T10:00:00.000Z',
    editedAt: null as string | null,
  },
  {
    id: 'act-004',
    entityType: 'LEAD' as const,
    entityId: 'led-001',
    actorId: DEMO_USER_ID,
    actorType: 'USER' as const,
    actorDisplayName: 'Demo User',
    kind: 'COMMENT' as const,
    action: 'comment.created',
    payload: {},
    changes: null,
    comment: 'Interested in pricing.',
    reason: null,
    parentActivityId: null,
    relatedTaskId: null,
    companyId: 'cmp-demo',
    createdAt: '2024-06-16T11:00:00.000Z',
    editedAt: null as string | null,
  },
  {
    id: 'act-005',
    entityType: 'LEAD' as const,
    entityId: 'led-001',
    actorId: DEMO_USER_ID,
    actorType: 'USER' as const,
    actorDisplayName: 'Demo User',
    kind: 'COMMENT' as const,
    action: 'comment.created',
    payload: {},
    changes: null,
    comment: 'Ask about setup timing on the intro call.',
    reason: null,
    parentActivityId: 'act-003',
    relatedTaskId: null,
    companyId: 'cmp-demo',
    createdAt: '2024-06-16T11:15:00.000Z',
    editedAt: null as string | null,
  },
];

export const DEMO_NOTIFICATIONS = [
  {
    id: 'notif-001',
    userId: DEMO_USER_ID,
    action: 'TASK_ASSIGNED' as const,
    entityType: 'TASK' as const,
    entityId: 'tsk-001',
    actorId: DEMO_USER_ID,
    actorName: 'Demo User',
    readAt: null as string | null,
    createdAt: '2024-09-01T10:00:00.000Z',
  },
  {
    id: 'notif-002',
    userId: DEMO_USER_ID,
    action: 'DEAL_ASSIGNED' as const,
    entityType: 'DEAL' as const,
    entityId: 'dea-001',
    actorId: DEMO_USER_ID,
    actorName: 'Demo User',
    readAt: null as string | null,
    createdAt: '2024-10-01T10:00:00.000Z',
  },
];

export const DEMO_TAGS = [
  { id: 'tag-001', companyId: 'cmp-demo', name: 'VIP', color: null as string | null },
  { id: 'tag-002', companyId: 'cmp-demo', name: 'Partner', color: null as string | null },
  { id: 'tag-003', companyId: 'cmp-demo', name: 'Newsletter', color: null as string | null },
];

export const DEMO_LEAD_SOURCES = [
  { id: 'ls-001', companyId: 'cmp-demo', name: 'Website' },
  { id: 'ls-002', companyId: 'cmp-demo', name: 'Referral' },
  { id: 'ls-003', companyId: 'cmp-demo', name: 'Social Media' },
];

export const DEMO_MEMBERSHIPS = [
  {
    id: 'mem-001',
    userId: DEMO_USER_ID,
    companyId: 'cmp-demo',
    role: 'OWNER' as const,
    isActive: true,
    createdAt: '2024-01-01T00:00:00.000Z',
    updatedAt: '2024-01-01T00:00:00.000Z',
    user: {
      id: DEMO_USER_ID,
      email: 'demo@alozix.com',
      firstName: 'Demo',
      lastName: 'User',
      avatarUrl: null as string | null,
    },
  },
];

export const DEMO_COMPANY_SETTINGS = {
  id: 'cmp-demo',
  name: 'Demo Company',
  timezone: 'UTC',
  businessHoursStart: '09:00',
  businessHoursEnd: '17:00',
  createdAt: '2024-01-01T00:00:00.000Z',
  updatedAt: '2024-01-01T00:00:00.000Z',
};

// Whatsapp demo conversations
export const DEMO_WA_CONVERSATIONS = [
  {
    id: 'wa-conv-001',
    provider: 'whatsapp',
    phoneNumber: '+15550201',
    displayName: 'Frank DemoLead',
    lastMessageAt: '2026-07-13T15:30:00.000Z',
    lastMessageBody: 'Hi, I am interested in your services.',
    unreadCount: 1,
    needsAttention: true,
    linkedContactId: null,
    linkedLeadId: 'led-001',
    crmContext: null,
  },
  {
    id: 'wa-conv-002',
    provider: 'whatsapp',
    phoneNumber: '+15550101',
    displayName: 'Alice Example',
    lastMessageAt: '2026-07-12T10:00:00.000Z',
    lastMessageBody: 'Thanks for the proposal!',
    unreadCount: 0,
    needsAttention: false,
    linkedContactId: 'cnt-001',
    linkedLeadId: null,
    crmContext: null,
  },
];
